- name: "setup workstation configurations"
  hosts: localhost
  vars:
    packages:
      RedHat:
        - konsole
        - git
        - gh
        - starship
  tasks:
    - name: "install packages via {{ ansible_pkg_mgr }}"
      package:
        state: "present"
        name:
          - "{{ 'konsole' if ansible_pkg_mgr in ['yum', 'apt', 'dnf'] else 'iterm2' }}"
          - git
          - gh
          - starship

      become: true
